[Network]
ExternalIP=127.0.0.1
InternalIP=0.0.0.0
AuthPort=9001
UnitPort=9002

[ChannelPorts]
; Format: ChannelID=Port
; If a channel from the database is not listed here, it won't be sent to the client.
1=9002

[Database]
ServerName=61.184.20.203
UserID=sa
Password=Ahtd!@123
GameDB=xiah
AccountDB=xiah_account
ServerDB=xiah_server
LogDB=xiah_log
