[Network]
ExternalIP=127.0.0.1
InternalIP=0.0.0.0
AuthPort=9001
UnitPort=9002
PatchPort=9005

[ChannelPorts]
; Format: ChannelID=Port
; If a channel from the database is not listed here, it won't be sent to the client.
1=9002

[Database]
ServerName=103.236.87.224
UserID=sa
Password=Xiah!@123
GameDB=xiah
AccountDB=xiah_account
ServerDB=xiah_server
LogDB=xiah_log
