#include <stdio.h>
#define OFFSET_CS 0x3100
#define OFFSET_CS_NC (OFFSET_CS + 0x0400)
#define OFFSET_CS_IM (OFFSET_CS + 0x0200)
#define OFFSET_CS_IT (OFFSET_CS + 0x1300)

#define CS_IT_CHARINFOLIST_REQ (OFFSET_CS_IT + 42)
#define CS_NC_NPCINFOLIST_REQ (OFFSET_CS_NC + 44)
#define CS_IM_MAPITEMINFOLIST_REQ (OFFSET_CS_IM + 48)
#define CS_NC_FUNCTIONALNPCINFOLIST_REQ (OFFSET_CS_NC + 48)
#define CS_NC_PETINFOLIST_REQ (OFFSET_CS_NC + 58)

int main() {
    printf(\"CS_IT_CHARINFOLIST_REQ = 0x%04X\n\", CS_IT_CHARINFOLIST_REQ);
    printf(\"CS_NC_NPCINFOLIST_REQ = 0x%04X\n\", CS_NC_NPCINFOLIST_REQ);
    printf(\"CS_IM_MAPITEMINFOLIST_REQ = 0x%04X\n\", CS_IM_MAPITEMINFOLIST_REQ);
    printf(\"CS_NC_FUNCTIONALNPCINFOLIST_REQ = 0x%04X\n\", CS_NC_FUNCTIONALNPCINFOLIST_REQ);
    printf(\"CS_NC_PETINFOLIST_REQ = 0x%04X\n\", CS_NC_PETINFOLIST_REQ);
    return 0;
}
